name: Test schedule

on:
  push:
    branches:
      - main
  schedule:
    - cron: "40 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: date
